# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Kyras\Google Drive\coding_projects\PyCharm\GifExtractor\data\options.ui'
#
# Created: Thu Apr 17 15:22:32 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_wnd_gifextract_options(object):
    def setupUi(self, wnd_gifextract_options):
        wnd_gifextract_options.setObjectName("wnd_gifextract_options")
        wnd_gifextract_options.resize(356, 262)
        wnd_gifextract_options.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(wnd_gifextract_options)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_ffmpegfolder = QtWidgets.QLineEdit(self.centralwidget)
        self.line_ffmpegfolder.setObjectName("line_ffmpegfolder")
        self.horizontalLayout.addWidget(self.line_ffmpegfolder)
        self.btn_ffmpegbrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ffmpegbrowse.setObjectName("btn_ffmpegbrowse")
        self.horizontalLayout.addWidget(self.btn_ffmpegbrowse)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_imfolder = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_imfolder.sizePolicy().hasHeightForWidth())
        self.line_imfolder.setSizePolicy(sizePolicy)
        self.line_imfolder.setMinimumSize(QtCore.QSize(0, 0))
        self.line_imfolder.setObjectName("line_imfolder")
        self.horizontalLayout_2.addWidget(self.line_imfolder)
        self.btn_imbrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_imbrowse.setObjectName("btn_imbrowse")
        self.horizontalLayout_2.addWidget(self.btn_imbrowse)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.check_fpsrounding = QtWidgets.QCheckBox(self.centralwidget)
        self.check_fpsrounding.setObjectName("check_fpsrounding")
        self.gridLayout.addWidget(self.check_fpsrounding, 0, 0, 1, 1)
        self.check_autoscan = QtWidgets.QCheckBox(self.centralwidget)
        self.check_autoscan.setObjectName("check_autoscan")
        self.gridLayout.addWidget(self.check_autoscan, 0, 1, 1, 1)
        self.check_usedurationalways = QtWidgets.QCheckBox(self.centralwidget)
        self.check_usedurationalways.setObjectName("check_usedurationalways")
        self.gridLayout.addWidget(self.check_usedurationalways, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spin_defaultdelay = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_defaultdelay.setObjectName("spin_defaultdelay")
        self.horizontalLayout_3.addWidget(self.spin_defaultdelay)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btn_saveconfig = QtWidgets.QPushButton(self.centralwidget)
        self.btn_saveconfig.setObjectName("btn_saveconfig")
        self.horizontalLayout_5.addWidget(self.btn_saveconfig)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        wnd_gifextract_options.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(wnd_gifextract_options)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 356, 21))
        self.menubar.setObjectName("menubar")
        wnd_gifextract_options.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(wnd_gifextract_options)
        self.statusbar.setObjectName("statusbar")
        wnd_gifextract_options.setStatusBar(self.statusbar)

        self.retranslateUi(wnd_gifextract_options)
        QtCore.QMetaObject.connectSlotsByName(wnd_gifextract_options)

    def retranslateUi(self, wnd_gifextract_options):
        _translate = QtCore.QCoreApplication.translate
        wnd_gifextract_options.setWindowTitle(_translate("wnd_gifextract_options", "GifExtract - Options"))
        self.label.setText(_translate("wnd_gifextract_options", "FFmpeg Bin Folder"))
        self.btn_ffmpegbrowse.setText(_translate("wnd_gifextract_options", "Browse"))
        self.label_2.setText(_translate("wnd_gifextract_options", "ImageMagick Bin Folder"))
        self.btn_imbrowse.setText(_translate("wnd_gifextract_options", "Browse"))
        self.check_fpsrounding.setText(_translate("wnd_gifextract_options", "Round Frames Per Second"))
        self.check_autoscan.setText(_translate("wnd_gifextract_options", "Automatically Scan Videos"))
        self.check_usedurationalways.setText(_translate("wnd_gifextract_options", "Always Use Duration Instead of Endtime"))
        self.label_4.setText(_translate("wnd_gifextract_options", "Gifs"))
        self.label_3.setText(_translate("wnd_gifextract_options", "Default Delay"))
        self.btn_saveconfig.setText(_translate("wnd_gifextract_options", "Save"))

