# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Kyras\Google Drive\coding_projects\PyCharm\GifExtractor\data\tab_gif.ui'
#
# Created: Thu Apr 17 18:49:02 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frame_tab_gif(object):
    def setupUi(self, frame_tab_gif):
        frame_tab_gif.setObjectName("frame_tab_gif")
        frame_tab_gif.resize(378, 241)
        frame_tab_gif.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame_tab_gif.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(frame_tab_gif)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(frame_tab_gif)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.cmb_job = QtWidgets.QComboBox(frame_tab_gif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_job.sizePolicy().hasHeightForWidth())
        self.cmb_job.setSizePolicy(sizePolicy)
        self.cmb_job.setObjectName("cmb_job")
        self.horizontalLayout.addWidget(self.cmb_job)
        self.btn_refreshjobs = QtWidgets.QPushButton(frame_tab_gif)
        self.btn_refreshjobs.setObjectName("btn_refreshjobs")
        self.horizontalLayout.addWidget(self.btn_refreshjobs)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(frame_tab_gif)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.cmb_loadgifsettings = QtWidgets.QComboBox(frame_tab_gif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_loadgifsettings.sizePolicy().hasHeightForWidth())
        self.cmb_loadgifsettings.setSizePolicy(sizePolicy)
        self.cmb_loadgifsettings.setEditable(False)
        self.cmb_loadgifsettings.setCurrentText("")
        self.cmb_loadgifsettings.setFrame(True)
        self.cmb_loadgifsettings.setObjectName("cmb_loadgifsettings")
        self.horizontalLayout.addWidget(self.cmb_loadgifsettings)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(frame_tab_gif)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.layout_resize = QtWidgets.QHBoxLayout()
        self.layout_resize.setObjectName("layout_resize")
        self.check_resize = QtWidgets.QCheckBox(frame_tab_gif)
        self.check_resize.setObjectName("check_resize")
        self.layout_resize.addWidget(self.check_resize)
        self.check_resize_keepratio = QtWidgets.QCheckBox(frame_tab_gif)
        self.check_resize_keepratio.setEnabled(False)
        self.check_resize_keepratio.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check_resize_keepratio.setObjectName("check_resize_keepratio")
        self.layout_resize.addWidget(self.check_resize_keepratio)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_resize.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.layout_resize)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_resize_width = QtWidgets.QLabel(frame_tab_gif)
        self.lbl_resize_width.setEnabled(False)
        self.lbl_resize_width.setObjectName("lbl_resize_width")
        self.horizontalLayout_3.addWidget(self.lbl_resize_width)
        self.lbl_resize_height = QtWidgets.QLabel(frame_tab_gif)
        self.lbl_resize_height.setEnabled(False)
        self.lbl_resize_height.setObjectName("lbl_resize_height")
        self.horizontalLayout_3.addWidget(self.lbl_resize_height)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(frame_tab_gif)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(frame_tab_gif)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.spin_delay = QtWidgets.QSpinBox(frame_tab_gif)
        self.spin_delay.setProperty("value", 24)
        self.spin_delay.setObjectName("spin_delay")
        self.horizontalLayout_4.addWidget(self.spin_delay)
        self.check_gif_loop = QtWidgets.QCheckBox(frame_tab_gif)
        self.check_gif_loop.setChecked(True)
        self.check_gif_loop.setObjectName("check_gif_loop")
        self.horizontalLayout_4.addWidget(self.check_gif_loop)
        self.check_gif_deletesource = QtWidgets.QCheckBox(frame_tab_gif)
        self.check_gif_deletesource.setObjectName("check_gif_deletesource")
        self.horizontalLayout_4.addWidget(self.check_gif_deletesource)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_5 = QtWidgets.QFrame(frame_tab_gif)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_creategif = QtWidgets.QPushButton(frame_tab_gif)
        self.btn_creategif.setObjectName("btn_creategif")
        self.horizontalLayout_5.addWidget(self.btn_creategif)
        self.btn_savegifsettings = QtWidgets.QPushButton(frame_tab_gif)
        self.btn_savegifsettings.setObjectName("btn_savegifsettings")
        self.horizontalLayout_5.addWidget(self.btn_savegifsettings)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_gif_currtask = QtWidgets.QLabel(frame_tab_gif)
        font = QtGui.QFont()
        font.setItalic(True)
        self.lbl_gif_currtask.setFont(font)
        self.lbl_gif_currtask.setObjectName("lbl_gif_currtask")
        self.horizontalLayout_6.addWidget(self.lbl_gif_currtask)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.progress_gif_sub = QtWidgets.QProgressBar(frame_tab_gif)
        self.progress_gif_sub.setProperty("value", 0)
        self.progress_gif_sub.setTextVisible(False)
        self.progress_gif_sub.setObjectName("progress_gif_sub")
        self.verticalLayout.addWidget(self.progress_gif_sub)
        spacerItem4 = QtWidgets.QSpacerItem(355, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

        self.retranslateUi(frame_tab_gif)
        self.cmb_loadgifsettings.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(frame_tab_gif)

    def retranslateUi(self, frame_tab_gif):
        _translate = QtCore.QCoreApplication.translate
        frame_tab_gif.setWindowTitle(_translate("frame_tab_gif", "Frame"))
        self.label_8.setText(_translate("frame_tab_gif", "Job"))
        self.btn_refreshjobs.setText(_translate("frame_tab_gif", "Refresh"))
        self.label_9.setText(_translate("frame_tab_gif", "Load Settings"))
        self.check_resize.setText(_translate("frame_tab_gif", "Resize"))
        self.check_resize_keepratio.setText(_translate("frame_tab_gif", "Maintain Proportions"))
        self.lbl_resize_width.setText(_translate("frame_tab_gif", "Width"))
        self.lbl_resize_height.setText(_translate("frame_tab_gif", "Height"))
        self.label_10.setText(_translate("frame_tab_gif", "Delay"))
        self.check_gif_loop.setText(_translate("frame_tab_gif", "Loop"))
        self.check_gif_deletesource.setText(_translate("frame_tab_gif", "Delete Source Images"))
        self.btn_creategif.setText(_translate("frame_tab_gif", "Create Gif"))
        self.btn_savegifsettings.setText(_translate("frame_tab_gif", "Save Settings"))
        self.lbl_gif_currtask.setText(_translate("frame_tab_gif", "Task Progress"))

