# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Kyras\Google Drive\coding_projects\PyCharm\GifExtractor\data\tab_video.ui'
#
# Created: Fri Apr 18 02:12:31 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frame_tab_video(object):
    def setupUi(self, frame_tab_video):
        frame_tab_video.setObjectName("frame_tab_video")
        frame_tab_video.resize(609, 296)
        frame_tab_video.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame_tab_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(frame_tab_video)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox = QtWidgets.QGroupBox(frame_tab_video)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_videoin = QtWidgets.QLineEdit(self.groupBox)
        self.line_videoin.setObjectName("line_videoin")
        self.horizontalLayout.addWidget(self.line_videoin)
        self.btn_browsevideofile = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_browsevideofile.setFont(font)
        self.btn_browsevideofile.setObjectName("btn_browsevideofile")
        self.horizontalLayout.addWidget(self.btn_browsevideofile)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setHorizontalSpacing(24)
        self.gridLayout.setObjectName("gridLayout")
        self.time_start = QtWidgets.QTimeEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_start.sizePolicy().hasHeightForWidth())
        self.time_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.time_start.setFont(font)
        self.time_start.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.time_start.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.time_start.setDisplayFormat("hh:mm:ss.zzz")
        self.time_start.setTime(QtCore.QTime(0, 0, 0))
        self.time_start.setObjectName("time_start")
        self.gridLayout.addWidget(self.time_start, 1, 0, 1, 1)
        self.lbl_endtime = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_endtime.setFont(font)
        self.lbl_endtime.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_endtime.setObjectName("lbl_endtime")
        self.gridLayout.addWidget(self.lbl_endtime, 0, 1, 1, 2)
        self.time_end = QtWidgets.QTimeEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.time_end.sizePolicy().hasHeightForWidth())
        self.time_end.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.time_end.setFont(font)
        self.time_end.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.time_end.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.time_end.setTime(QtCore.QTime(0, 0, 0))
        self.time_end.setObjectName("time_end")
        self.gridLayout.addWidget(self.time_end, 1, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.chk_vidprefdur = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.chk_vidprefdur.setFont(font)
        self.chk_vidprefdur.setAutoFillBackground(False)
        self.chk_vidprefdur.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.chk_vidprefdur.setText("")
        self.chk_vidprefdur.setObjectName("chk_vidprefdur")
        self.gridLayout.addWidget(self.chk_vidprefdur, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_6.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(frame_tab_video)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_vidanalyze = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_vidanalyze.sizePolicy().hasHeightForWidth())
        self.btn_vidanalyze.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_vidanalyze.setFont(font)
        self.btn_vidanalyze.setObjectName("btn_vidanalyze")
        self.verticalLayout.addWidget(self.btn_vidanalyze)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.cmb_subs = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_subs.sizePolicy().hasHeightForWidth())
        self.cmb_subs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cmb_subs.setFont(font)
        self.cmb_subs.setObjectName("cmb_subs")
        self.horizontalLayout_2.addWidget(self.cmb_subs)
        self.btn_loadsubs = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_loadsubs.setFont(font)
        self.btn_loadsubs.setObjectName("btn_loadsubs")
        self.horizontalLayout_2.addWidget(self.btn_loadsubs)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.line_fps = QtWidgets.QLineEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_fps.setFont(font)
        self.line_fps.setObjectName("line_fps")
        self.horizontalLayout_3.addWidget(self.line_fps)
        self.cmb_fps = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_fps.sizePolicy().hasHeightForWidth())
        self.cmb_fps.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cmb_fps.setFont(font)
        self.cmb_fps.setModelColumn(0)
        self.cmb_fps.setObjectName("cmb_fps")
        self.horizontalLayout_3.addWidget(self.cmb_fps)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_extract_exe = QtWidgets.QPushButton(frame_tab_video)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_extract_exe.setFont(font)
        self.btn_extract_exe.setObjectName("btn_extract_exe")
        self.horizontalLayout_4.addWidget(self.btn_extract_exe)
        self.btn_extract_queue = QtWidgets.QPushButton(frame_tab_video)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.btn_extract_queue.setFont(font)
        self.btn_extract_queue.setObjectName("btn_extract_queue")
        self.horizontalLayout_4.addWidget(self.btn_extract_queue)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_4 = QtWidgets.QLabel(frame_tab_video)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.progbar_videoextract = QtWidgets.QProgressBar(frame_tab_video)
        self.progbar_videoextract.setProperty("value", 0)
        self.progbar_videoextract.setTextVisible(False)
        self.progbar_videoextract.setObjectName("progbar_videoextract")
        self.horizontalLayout_5.addWidget(self.progbar_videoextract)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)

        self.retranslateUi(frame_tab_video)
        QtCore.QMetaObject.connectSlotsByName(frame_tab_video)

    def retranslateUi(self, frame_tab_video):
        _translate = QtCore.QCoreApplication.translate
        frame_tab_video.setWindowTitle(_translate("frame_tab_video", "Frame"))
        self.groupBox.setTitle(_translate("frame_tab_video", "Video Source"))
        self.label.setText(_translate("frame_tab_video", "Video File"))
        self.btn_browsevideofile.setText(_translate("frame_tab_video", "Browse"))
        self.lbl_endtime.setText(_translate("frame_tab_video", "End Time"))
        self.time_end.setDisplayFormat(_translate("frame_tab_video", "hh:mm:ss.zzz"))
        self.label_2.setText(_translate("frame_tab_video", "Use Duration Instead Of End Time"))
        self.label_3.setText(_translate("frame_tab_video", "Start Time"))
        self.groupBox_2.setTitle(_translate("frame_tab_video", "Additional Settings"))
        self.btn_vidanalyze.setText(_translate("frame_tab_video", "Analyze Video"))
        self.label_5.setText(_translate("frame_tab_video", "Subtitles"))
        self.btn_loadsubs.setText(_translate("frame_tab_video", "Load External Subs"))
        self.label_6.setText(_translate("frame_tab_video", "Frame Rate"))
        self.btn_extract_exe.setText(_translate("frame_tab_video", "Execute"))
        self.btn_extract_queue.setText(_translate("frame_tab_video", "Add To Queue"))
        self.label_4.setText(_translate("frame_tab_video", "Task Progress"))

