# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Kyras\Google Drive\coding_projects\PyCharm\GifExtractor\data\tab_gif.ui'
#
# Created: Fri Apr 18 01:20:34 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_frame_tab_gif(object):
    def setupUi(self, frame_tab_gif):
        frame_tab_gif.setObjectName("frame_tab_gif")
        frame_tab_gif.setEnabled(True)
        frame_tab_gif.resize(474, 504)
        frame_tab_gif.setFrameShape(QtWidgets.QFrame.StyledPanel)
        frame_tab_gif.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(frame_tab_gif)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(frame_tab_gif)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.cmb_job = QtWidgets.QComboBox(frame_tab_gif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_job.sizePolicy().hasHeightForWidth())
        self.cmb_job.setSizePolicy(sizePolicy)
        self.cmb_job.setObjectName("cmb_job")
        self.horizontalLayout.addWidget(self.cmb_job)
        self.btn_refreshjobs = QtWidgets.QPushButton(frame_tab_gif)
        self.btn_refreshjobs.setObjectName("btn_refreshjobs")
        self.horizontalLayout.addWidget(self.btn_refreshjobs)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_9 = QtWidgets.QLabel(frame_tab_gif)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.cmb_loadgifsettings = QtWidgets.QComboBox(frame_tab_gif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_loadgifsettings.sizePolicy().hasHeightForWidth())
        self.cmb_loadgifsettings.setSizePolicy(sizePolicy)
        self.cmb_loadgifsettings.setEditable(False)
        self.cmb_loadgifsettings.setCurrentText("")
        self.cmb_loadgifsettings.setFrame(True)
        self.cmb_loadgifsettings.setObjectName("cmb_loadgifsettings")
        self.horizontalLayout.addWidget(self.cmb_loadgifsettings)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.group_resize = QtWidgets.QGroupBox(frame_tab_gif)
        self.group_resize.setObjectName("group_resize")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.group_resize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.check_resize = QtWidgets.QCheckBox(self.group_resize)
        self.check_resize.setObjectName("check_resize")
        self.horizontalLayout_2.addWidget(self.check_resize)
        self.check_resize_keepratio = QtWidgets.QCheckBox(self.group_resize)
        self.check_resize_keepratio.setEnabled(False)
        self.check_resize_keepratio.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check_resize_keepratio.setChecked(True)
        self.check_resize_keepratio.setObjectName("check_resize_keepratio")
        self.horizontalLayout_2.addWidget(self.check_resize_keepratio)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.layout_resize = QtWidgets.QHBoxLayout()
        self.layout_resize.setObjectName("layout_resize")
        self.lbl_resize_width = QtWidgets.QLabel(self.group_resize)
        self.lbl_resize_width.setEnabled(False)
        self.lbl_resize_width.setObjectName("lbl_resize_width")
        self.layout_resize.addWidget(self.lbl_resize_width)
        self.lbl_resize_height = QtWidgets.QLabel(self.group_resize)
        self.lbl_resize_height.setEnabled(False)
        self.lbl_resize_height.setObjectName("lbl_resize_height")
        self.layout_resize.addWidget(self.lbl_resize_height)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_resize.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.layout_resize)
        self.horizontalLayout_7.addWidget(self.group_resize)
        self.group_gifsettings = QtWidgets.QGroupBox(frame_tab_gif)
        self.group_gifsettings.setObjectName("group_gifsettings")
        self.formLayout_4 = QtWidgets.QFormLayout(self.group_gifsettings)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_10 = QtWidgets.QLabel(self.group_gifsettings)
        self.label_10.setObjectName("label_10")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.spin_delay = QtWidgets.QSpinBox(self.group_gifsettings)
        self.spin_delay.setProperty("value", 24)
        self.spin_delay.setObjectName("spin_delay")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spin_delay)
        self.spin_loops = QtWidgets.QSpinBox(self.group_gifsettings)
        self.spin_loops.setObjectName("spin_loops")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_loops)
        self.label_3 = QtWidgets.QLabel(self.group_gifsettings)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_7.addWidget(self.group_gifsettings)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(frame_tab_gif)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.radio_size = QtWidgets.QRadioButton(frame_tab_gif)
        self.radio_size.setChecked(True)
        self.radio_size.setObjectName("radio_size")
        self.buttonGroup = QtWidgets.QButtonGroup(frame_tab_gif)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radio_size)
        self.horizontalLayout_6.addWidget(self.radio_size)
        self.radio_quality = QtWidgets.QRadioButton(frame_tab_gif)
        self.radio_quality.setObjectName("radio_quality")
        self.buttonGroup.addButton(self.radio_quality)
        self.horizontalLayout_6.addWidget(self.radio_quality)
        self.radio_balanced = QtWidgets.QRadioButton(frame_tab_gif)
        self.radio_balanced.setObjectName("radio_balanced")
        self.buttonGroup.addButton(self.radio_balanced)
        self.horizontalLayout_6.addWidget(self.radio_balanced)
        self.radio_custom = QtWidgets.QRadioButton(frame_tab_gif)
        self.radio_custom.setObjectName("radio_custom")
        self.buttonGroup.addButton(self.radio_custom)
        self.horizontalLayout_6.addWidget(self.radio_custom)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.group_advsettings = QtWidgets.QGroupBox(frame_tab_gif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_advsettings.sizePolicy().hasHeightForWidth())
        self.group_advsettings.setSizePolicy(sizePolicy)
        self.group_advsettings.setCheckable(False)
        self.group_advsettings.setChecked(False)
        self.group_advsettings.setObjectName("group_advsettings")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.group_advsettings)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.group_advsettings)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.cmb_optimizationmethod = QtWidgets.QComboBox(self.groupBox_2)
        self.cmb_optimizationmethod.setEnabled(True)
        self.cmb_optimizationmethod.setObjectName("cmb_optimizationmethod")
        self.cmb_optimizationmethod.addItem("")
        self.cmb_optimizationmethod.addItem("")
        self.cmb_optimizationmethod.addItem("")
        self.cmb_optimizationmethod.addItem("")
        self.cmb_optimizationmethod.addItem("")
        self.cmb_optimizationmethod.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmb_optimizationmethod)
        self.check_nocomments = QtWidgets.QCheckBox(self.groupBox_2)
        self.check_nocomments.setObjectName("check_nocomments")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.check_nocomments)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setEnabled(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox_3)
        self.horizontalLayout_9.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.group_advsettings)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.check_usefuzz = QtWidgets.QCheckBox(self.groupBox_3)
        self.check_usefuzz.setObjectName("check_usefuzz")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.check_usefuzz)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setEnabled(False)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spin_fuzzfactor = QtWidgets.QSpinBox(self.groupBox_3)
        self.spin_fuzzfactor.setEnabled(False)
        self.spin_fuzzfactor.setMinimum(1)
        self.spin_fuzzfactor.setMaximum(100)
        self.spin_fuzzfactor.setObjectName("spin_fuzzfactor")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_fuzzfactor)
        self.check_flattencolors = QtWidgets.QCheckBox(self.groupBox_3)
        self.check_flattencolors.setObjectName("check_flattencolors")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.check_flattencolors)
        self.check_noaa = QtWidgets.QCheckBox(self.groupBox_3)
        self.check_noaa.setEnabled(True)
        self.check_noaa.setChecked(False)
        self.check_noaa.setObjectName("check_noaa")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.check_noaa)
        self.horizontalLayout_9.addWidget(self.groupBox_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addWidget(self.group_advsettings)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_5 = QtWidgets.QGroupBox(frame_tab_gif)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_gif_deletesource = QtWidgets.QCheckBox(self.groupBox_5)
        self.check_gif_deletesource.setObjectName("check_gif_deletesource")
        self.verticalLayout.addWidget(self.check_gif_deletesource)
        self.horizontalLayout_10.addWidget(self.groupBox_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.line_console = QtWidgets.QLineEdit(frame_tab_gif)
        self.line_console.setObjectName("line_console")
        self.verticalLayout_3.addWidget(self.line_console)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_creategif = QtWidgets.QPushButton(frame_tab_gif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_creategif.sizePolicy().hasHeightForWidth())
        self.btn_creategif.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_creategif.setFont(font)
        self.btn_creategif.setObjectName("btn_creategif")
        self.horizontalLayout_5.addWidget(self.btn_creategif)
        self.btn_savegifsettings = QtWidgets.QPushButton(frame_tab_gif)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_savegifsettings.sizePolicy().hasHeightForWidth())
        self.btn_savegifsettings.setSizePolicy(sizePolicy)
        self.btn_savegifsettings.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_savegifsettings.setObjectName("btn_savegifsettings")
        self.horizontalLayout_5.addWidget(self.btn_savegifsettings)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.lbl_gif_currtask = QtWidgets.QLabel(frame_tab_gif)
        font = QtGui.QFont()
        font.setItalic(True)
        self.lbl_gif_currtask.setFont(font)
        self.lbl_gif_currtask.setObjectName("lbl_gif_currtask")
        self.verticalLayout_3.addWidget(self.lbl_gif_currtask)
        self.progress_gif_sub = QtWidgets.QProgressBar(frame_tab_gif)
        self.progress_gif_sub.setProperty("value", 0)
        self.progress_gif_sub.setTextVisible(False)
        self.progress_gif_sub.setObjectName("progress_gif_sub")
        self.verticalLayout_3.addWidget(self.progress_gif_sub)
        spacerItem8 = QtWidgets.QSpacerItem(355, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)

        self.retranslateUi(frame_tab_gif)
        self.cmb_loadgifsettings.setCurrentIndex(-1)
        self.check_resize.clicked['bool'].connect(self.check_resize_keepratio.setEnabled)
        self.check_resize.clicked['bool'].connect(self.lbl_resize_width.setEnabled)
        self.check_resize.clicked['bool'].connect(self.lbl_resize_height.setEnabled)
        self.check_usefuzz.clicked['bool'].connect(self.label_5.setEnabled)
        self.check_usefuzz.clicked['bool'].connect(self.spin_fuzzfactor.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(frame_tab_gif)
        frame_tab_gif.setTabOrder(self.cmb_job, self.btn_refreshjobs)
        frame_tab_gif.setTabOrder(self.btn_refreshjobs, self.cmb_loadgifsettings)
        frame_tab_gif.setTabOrder(self.cmb_loadgifsettings, self.check_resize)
        frame_tab_gif.setTabOrder(self.check_resize, self.check_resize_keepratio)
        frame_tab_gif.setTabOrder(self.check_resize_keepratio, self.spin_delay)
        frame_tab_gif.setTabOrder(self.spin_delay, self.cmb_optimizationmethod)
        frame_tab_gif.setTabOrder(self.cmb_optimizationmethod, self.btn_creategif)
        frame_tab_gif.setTabOrder(self.btn_creategif, self.btn_savegifsettings)

    def retranslateUi(self, frame_tab_gif):
        _translate = QtCore.QCoreApplication.translate
        frame_tab_gif.setWindowTitle(_translate("frame_tab_gif", "Frame"))
        self.label_8.setText(_translate("frame_tab_gif", "Job"))
        self.btn_refreshjobs.setText(_translate("frame_tab_gif", "Refresh"))
        self.label_9.setText(_translate("frame_tab_gif", "Load Settings"))
        self.group_resize.setTitle(_translate("frame_tab_gif", "Resize Options"))
        self.check_resize.setText(_translate("frame_tab_gif", "Resize"))
        self.check_resize_keepratio.setText(_translate("frame_tab_gif", "Maintain Proportions"))
        self.lbl_resize_width.setText(_translate("frame_tab_gif", "Width"))
        self.lbl_resize_height.setText(_translate("frame_tab_gif", "Height"))
        self.group_gifsettings.setTitle(_translate("frame_tab_gif", "Gif Settings"))
        self.label_10.setText(_translate("frame_tab_gif", "Frame Rate"))
        self.label_3.setText(_translate("frame_tab_gif", "Maximum Loops (0=∞)"))
        self.label_2.setText(_translate("frame_tab_gif", "Settings:"))
        self.radio_size.setText(_translate("frame_tab_gif", "Size"))
        self.radio_quality.setText(_translate("frame_tab_gif", "Quality"))
        self.radio_balanced.setText(_translate("frame_tab_gif", "Balanced"))
        self.radio_custom.setText(_translate("frame_tab_gif", "Custom"))
        self.group_advsettings.setTitle(_translate("frame_tab_gif", "Advanced Settings"))
        self.groupBox_2.setTitle(_translate("frame_tab_gif", "Gif Optimization"))
        self.label_4.setText(_translate("frame_tab_gif", "Optimization Method"))
        self.cmb_optimizationmethod.setItemText(0, _translate("frame_tab_gif", "None"))
        self.cmb_optimizationmethod.setItemText(1, _translate("frame_tab_gif", "OptimizeFrame & OptimizeTransparency"))
        self.cmb_optimizationmethod.setItemText(2, _translate("frame_tab_gif", "OptimizePlus & OptimizeTransparency"))
        self.cmb_optimizationmethod.setItemText(3, _translate("frame_tab_gif", "OptimizePlus"))
        self.cmb_optimizationmethod.setItemText(4, _translate("frame_tab_gif", "OptimizeFrame"))
        self.cmb_optimizationmethod.setItemText(5, _translate("frame_tab_gif", "OptimizeTransparency"))
        self.check_nocomments.setText(_translate("frame_tab_gif", "Remove Comments"))
        self.checkBox_3.setText(_translate("frame_tab_gif", "Remove Duplicate Frames"))
        self.groupBox_3.setTitle(_translate("frame_tab_gif", "Color Optimization"))
        self.check_usefuzz.setText(_translate("frame_tab_gif", "Apply Color Fuzz"))
        self.label_5.setText(_translate("frame_tab_gif", "Fuzz Factor"))
        self.check_flattencolors.setText(_translate("frame_tab_gif", "Flatten Color Tables"))
        self.check_noaa.setText(_translate("frame_tab_gif", "Disable Anti-Aliasing"))
        self.groupBox_5.setTitle(_translate("frame_tab_gif", "File Settings"))
        self.check_gif_deletesource.setToolTip(_translate("frame_tab_gif", "INDEV"))
        self.check_gif_deletesource.setText(_translate("frame_tab_gif", "Delete Original Images"))
        self.btn_creategif.setText(_translate("frame_tab_gif", "Create Gif"))
        self.btn_savegifsettings.setText(_translate("frame_tab_gif", "Save Settings"))
        self.lbl_gif_currtask.setText(_translate("frame_tab_gif", "Task Progress"))

